[_]
schema-version = "0.2"

[com.salesforce]
schema-version = "0.1"
id = "chargingstations"
description = "List charging stations given a geographic location"
type = "function"
salesforce-api-version = "54.0"
