[_]
schema-version = "0.2"

[com.salesforce]
schema-version = "0.1"
id = "jobmanager"
description = "Orchestrates the execution of asynchronous jobs."
type = "function"
salesforce-api-version = "54.0"
