[_]
schema-version = "0.2"

[com.salesforce]
schema-version = "0.1"
id = "routeplanner"
description = "A Function that uses the Travel Salesman Problem to calculate deliveries"
type = "function"
salesforce-api-version = "54.0"